version: "3.1"
services:
  mysql:
    image: mysql:8.0.29
    container_name: mysql
    volumes:
      - "${MYSQLDBCONT_DATA_DIR:-/var/lib/mysql}:/var/lib/mysql"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=database
    networks:
      - develop-network
  www:
    build: .
    container_name: www
    volumes:
      - "${CONT_PROJECTS_DIR:-./prototipo-huella-hidrica}:/var/www/html"
      - "${CONT_PHP_CONF_DIR:-./php-config}:/etc/www-local-config"
      - "${HOME}:${HOME}"
    ports:
      - "${CONT_PORT:-80}:80"
    networks:
      - develop-network
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=pass
    networks:
      - develop-network
networks:
  develop-network:
